### PR TITLE
Added bytes support

### LINKED ISSUE #127: Use `bytes` package for human readable parsing of `limits`
Basically the `limits` option should detect if the values passed are Strings, and if they are, then parse them using the `bytes` package at <https://www.npmjs.com/package/bytes>.

Less math and less room for error!

Related: https://github.com/expressjs/multer/issues/401

### PR DESCRIPTION
**Pull request by niftylettuce**
Closes #127 and adds support for <https://github.com/expressjs/multer/issues/401>.

### CODE REVIEW

**Comment by charmander** [comment]
You can do this without adding complexity and a dependency:

```javascript
var Busboy = require('busboy');
var bytes = require('bytes');

var busboy = new Busboy({
    headers: req.headers,
    limits: {
        fileSize: bytes.parse('10mb'),
    },
});
```

**Comment by mscdex** [comment]
I'm not keen on adding a dependency just for this convenience. As @charmander points out, this is easily done without this change to `busboy`.

**Comment by niftylettuce** [comment]
Other packages widely used like https://github.com/expressjs/body-parser do this though.  It's nice for making packages simple to use by end-users.

**Comment by mscdex** [comment]
I'm aware that other projects do use such modules, but in general I strive to keep dependency counts low to minimize footprint and feature creep. In this particular case I wouldn't be able to justify adding this dependency for the little value (IMHO) that it brings.

**Comment by niftylettuce** [comment]
I feel like a ton of end users don't know about `bytes` and have math of
byte calculations written out in their apps with room for error...  I've
seen this in some of the biggest dev shops too.

**Comment by mscdex** [comment]
Module discovery is a general npm issue. Adding a dependency here won't help solve that problem, especially since users passing in a shorthand string value may not know that a separate module is allowing that to work (unless they inspect dependencies and/or the `busboy` source code -- which most people would not do).

I'm not sure how you could really go wrong with calculations, at least as far as using power-of-10 vs power-of-2 values goes. If you use a power of 2, then you're technically using the correct calculation. If you're using a power of 10, you'd actually be using a *smaller* value, which is better than accidentally allowing a *larger* value for a byte limit.

**Comment by niftylettuce** [comment]
I guess I'll just fork this package.  It's really a matter of simplifying
your API for end users, not writing the most lightweight package ever that
barely does anything and seems to be unmaintained with the open issues and
PRs.  Bytes is super small anyways...

**Comment by mscdex** [comment]
"that barely does anything" is quite a stretch :-)

Feel free to fork though, nobody is stopping you. That's the beauty of open source!

Closing this for now.

**Pull request closed without merging**
