### PR TITLE
Fix #121 : require explicitly supported content types

### LINKED ISSUE #121: Link to developer files when dependency is bundled
Hello !

Thank you for the time and effort you put in this project :)
We used your project recently and we encountered an issue when starting our node server :
```
~/dev/my_project/release • node server.js
fs.js:856
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/abalhier/dev/my_project/node_modules/busboy/lib/types'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.<anonymous> (/Users/abalhier/dev/my_project/release/server.js:10960:4)
    at Object.__dirname.13.module.exports.extractFormDataInputHierachy.28../utils (/Users/abalhier/dev/my_project/release/server.js:10972:4)
    at s (/Users/abalhier/dev/my_project/release/server.js:1:316)
    at /Users/abalhier/dev/my_project/release/server.js:1:367
    at Object.__dirname.13.module.exports.objectFromHierarchyArray.busboy (/Users/abalhier/dev/my_project/release/server.js:1614:16)
    at s (/Users/abalhier/dev/my_project/release/server.js:1:316)
    at /Users/abalhier/dev/my_project/release/server.js:1:367
    at Object.__dirname.13.module.exports.extractFormDataInputHierachy.252.exports.254.257.passport.263.623.../authentication/authentication (/Users/abalhier/dev/my_project/release/server.js:118103:20)
```

We are bundling dependencies and our code with node-browserify which may not be the traditional way to deploy and run node servers, but we feel this issue could be resolved easily by removing the use of __dirname.
Can you take a look at the pull request I am submitting ?

### PR DESCRIPTION
**Pull request by abalhier**

### CODE REVIEW

**Comment by mscdex** [comment]
Landed in 76c3d588b0560f34f092ff57b84869f2e077f4d3. Thanks!

**Comment by ahumbledeveloper** [comment]
Nice one fixing this @abalhier.

@mscdex, do you know when this will be released?

**Comment by jeremejevs** [comment]
Would be nice to have this released. I'm not using `busboy` directly, but rather through `async-busboy`, so I'm forced to modify `yarn.lock` manually, which is normally a no-no.

**Comment by mscdex** [comment]
Done.

**Comment by jeremejevs** [comment]
Thanks, appreciate it!

**Pull request closed without merging**
