### PR TITLE
Document constructor exceptions

### PR DESCRIPTION
**Pull request by kemitchell**
Thanks so much for Busboy!

This tiny PR adds a short summary of the kinds of exceptions `new Busyboy({ headers: req.headers })` might throw to the end of the API section of the README.

If you think it's worthwhile, I'd be happy to push another commit to add some sanity checking the other README examples, to show that you might want to be sure you've received the _kind_ of POST you expect before creating a Busboy object.

@jimmywarting's original post in #84 raises an interesting question about whether Busboy should throw these errors, or rather emit them as events. I'm not sure what the right answer is.

The documentation additions in this PR describe the way things are now.

Best,

K

### CODE REVIEW

**Comment by mscdex** [comment]
Perhaps this information is better placed in the constructor description somehow? It looks out of place having it separate it like that.

Documenting this is a little tricky though since there are both exceptions common to all (2) supported `Content-Type`s as well as `Content-Type`-specific exceptions (like missing boundary for multipart).

**Comment by mscdex** [comment]
As far as error handling goes, I'm generally more a fan of failing as fast as possible (which means immediately throwing an exception before reaching the end of the function, either directly or indirectly). However if it's really that big of a deal to people, I may be open to switching to using `error` events. My argument against it is that it just delays the inevitable and gives a (short) false sense of success (since the `error` emitting would have to be done on next tick).

**Comment by jimmywarting** [comment]
I generally felt like a try/catch is a boost kill, since v8 can't optimise them. That is why I raises my question a long time ago. But knowing how to deal with them in demos, docs or this readme file would be a great way to help others. Just by knowing that this module can throw errors means you have to wrap it in a try/catch (that is not something i take for granted)

Sometimes frameworks & modules deal with them for you so your app don't crash.
The node eco system it's often a error as first argument in a callback... or a promise rejection.

**Comment by kemitchell** [comment]
Pushed an additional commit consolidating the list of errors with the section describing the constructor.

**Comment by mscdex** [comment]
Landed in cb4dbc9da88ef7f96514b7c88732a652904af05d. Thanks!

**Pull request closed without merging**
