### PR TITLE
Avoid using global Buffer

### PR DESCRIPTION
**Pull request by jimmywarting**

### CODE REVIEW

**Comment by mscdex** [comment]
Why?

**Comment by jimmywarting** [comment]
trying to assume that it exist globally is problematic for bundlers. it needs to scan the code if one is using globalThis.buffer and needs to decide if it have to polyfill it or not.

- using global buffer/process is an anti-patern according to https://github.com/nodejs/node/pull/26334
- NodeJS own docs recommend importing it: https://nodejs.org/api/buffer.html#buffer_buffer instead of depending on global.Buffer
- it was once attempted to warn/deprecate access to globalThis.buffer by assigning it a deprecation warning getter function.

my own code can detect this kinds of patterns where ppl try to use globalThis.buffer and yours is one of them

**Comment by jimmywarting** [comment]
In any case i think you should attempt to only use Uint8Array instead of the overhead Buffer if at all possible.

**Comment by mscdex** [comment]
> In any case i think you should attempt to only use Uint8Array instead of the overhead Buffer if at all possible.

That's not very feasible considering:

* This module utilizes Buffer-specific functionality
* Node.js users are more accustomed to dealing with Buffers at this point
* Working around the limitations of Uint8Array would not only require adding more code to polyfill functionality but it could also easily result in lower performance

**Pull request closed without merging**
